---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 2-demo-kustomization-git-bb-app
  namespace: flux-system
spec:
  interval: 10s
  path: ./manifests
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: 2-demo-src-git-bb-app
  targetNamespace: 2-demo
  timeout: 3m0s
  wait: true
